"""empty message

Revision ID: 906793d5004b
Revises: c62a6f818757
Create Date: 2022-12-15 18:18:37.125270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906793d5004b'
down_revision = 'c62a6f818757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customusers', sa.Column('username', sa.String(length=20), nullable=False))
    op.drop_column('customusers', 'last_name')
    op.drop_column('customusers', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customusers', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('customusers', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('customusers', 'username')
    # ### end Alembic commands ###
